# ============================================================
# File: tools/project_index.py
# Purpose:
# - Builds a lightweight source-code index for AI-assisted development.
# ============================================================

import ast
from dataclasses import dataclass
from pathlib import Path


ROOT_DIR = Path.cwd()
APP_DIR = ROOT_DIR / "app"
OUTPUT_PATH = ROOT_DIR / "_code_review" / "project_index.md"


@dataclass(frozen=True)
class PythonFileIndex:
    path: Path
    classes: list[str]
    functions: list[str]
    imports: list[str]


def safe_parse_python(path: Path):
    try:
        return ast.parse(path.read_text(encoding="utf-8"))
    except UnicodeDecodeError:
        return ast.parse(path.read_text(encoding="cp1251"))
    except Exception as exc:
        print(f"[warn] cannot parse {path}: {exc}")
        return None


def collect_import_name(node):
    if isinstance(node, ast.Import):
        return ", ".join(alias.name for alias in node.names)

    if isinstance(node, ast.ImportFrom):
        module = node.module or ""
        names = ", ".join(alias.name for alias in node.names)
        return f"from {module} import {names}"

    return None


def index_python_file(path: Path) -> PythonFileIndex:
    tree = safe_parse_python(path)

    if tree is None:
        return PythonFileIndex(path=path, classes=[], functions=[], imports=[])

    classes = []
    functions = []
    imports = []

    for node in tree.body:
        import_name = collect_import_name(node)

        if import_name:
            imports.append(import_name)

        if isinstance(node, ast.ClassDef):
            classes.append(node.name)

        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            functions.append(node.name)

    return PythonFileIndex(
        path=path,
        classes=classes,
        functions=functions,
        imports=imports,
    )


def iter_project_python_files():
    if not APP_DIR.exists():
        raise FileNotFoundError(f"App directory not found: {APP_DIR}")

    return [
        path
        for path in sorted(APP_DIR.rglob("*.py"))
        if "__pycache__" not in path.parts
    ]


def render_markdown(indexes):
    lines = [
        "# Project Index",
        "",
        "Generated by tools/project_index.py.",
        "",
        f"Total Python files: {len(indexes)}",
        "",
    ]

    for item in indexes:
        rel_path = item.path.relative_to(ROOT_DIR).as_posix()

        lines.append(f"## {rel_path}")
        lines.append("")

        if item.classes:
            lines.append("### Classes")
            for class_name in item.classes:
                lines.append(f"- {class_name}")
            lines.append("")

        if item.functions:
            lines.append("### Functions")
            for function_name in item.functions:
                lines.append(f"- {function_name}")
            lines.append("")

        if item.imports:
            lines.append("### Imports")
            for import_name in item.imports[:20]:
                lines.append(f"- {import_name}")
            if len(item.imports) > 20:
                lines.append(f"- ... {len(item.imports) - 20} more")
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main():
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    files = iter_project_python_files()
    indexes = [index_python_file(path) for path in files]

    OUTPUT_PATH.write_text(render_markdown(indexes), encoding="utf-8")

    print(f"[ok] project index written to: {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
